<?header ("Content-Type: text/html; charset=utf-8");?>
<?
$type=$_GET["type"];
$id_product=$_GET["id_product"];
$id_bask=$_COOKIE["id_bask"];
include ("connect.phtml");
if ($type==1)
{
	$strSQL="SELECT * FROM basket WHERE id_product=".$id_product." AND id_bask='".$id_bask."'";
	$result=mysql_query($strSQL) or die ("Не могу выполнить запрос1!");
	if ($row=mysql_fetch_array($result))
	{
		$strSQL="UPDATE basket SET quantity=quantity+1 WHERE id_product=".$id_product." AND id_bask='".$id_bask."'";
	}
	else
	{
		$strSQL="INSERT INTO basket (id_bask,id_product,quantity) VALUES ('".$id_bask."',".$id_product.",1)";
	}
	mysql_query($strSQL);
}
else 
	if($type==2)
	{
		$strSQL="SELECT * FROM basket WHERE id_product=".$id_product." AND id_bask='".$id_bask."'";
		$result=mysql_query($strSQL) or die ("Не могу выполнить запрос1!");
		if ($row=mysql_fetch_array($result))
		{
			if ($row["quantity"]>1)
			{
				$strSQL="UPDATE basket SET quantity=quantity-1 WHERE id_product=".$id_product." AND id_bask='".$id_bask."'";
			}
			else 
			{
				$strSQL="DELETE FROM basket WHERE id_product=".$id_product." AND id_bask='".$id_bask."'";
			}
		}
		mysql_query($strSQL);
	}
	else 
	if($type==3)
		{
			$strSQL="DELETE FROM basket WHERE id_product=".$id_product." AND id_bask='".$id_bask."'";
			mysql_query($strSQL);
		}
	else
	if($type==4)
	{
		$strSQL="DELETE FROM basket WHERE id_bask='".$id_bask."'";
		mysql_query($strSQL);
	}
	include("basket.phtml");
?>
			