<?header ("Content-Type: text/html; charset=utf-8");?>
<?
$log=$_SESSION["login"];
$id=$_SESSION["id"];
$id_bask=$_COOKIE["id_bask"];
$export=$_POST["export"];

$title="Заказ";
$color="#66cc66";
include("connect.phtml");
if(!isset($log))
	$message="<tr><td bgcolor='#ff9999' align = 'center'>
Вы не авторизованы </td></tr>";
else
{
	$strSQL1="SELECT COUNT(*) as quantity FROM basket WHERE id_bask='".$id_bask."'";
	$result1=mysql_query($strSQL1) or die ("НЕ могу выполнить запрос2");
	$row=mysql_fetch_array($result1);
	if($row["quantity"]==0)
		$message="<tr><td bgcolor='#ff9999' align='center'>
	Ваша корзина пуста </td></tr>";
	else{
		$order=uniqid("OR");
		$strSQL="INSERT INTO orders(id_order,date_ord,id_cust) VALUES ('".$order."',CURDATE(),".$id.")";
		mysql_query($strSQL) or die ("НЕ могу выполнить запрос 1");
		$strSQL="SELECT * FROM basket WHERE id_bask='".$id_bask."'";
		$result=mysql_query($strSQL) or die ("НЕ могу выполнить запрос2");
	while ($row=mysql_fetch_array($result))
	{
		$strSQL="INSERT INTO order_optics(id_order,id_product,quantity)
		VALUES ('".$order."',".$row["id_product"].",".$row["quantity"].")";
		mysql_query($strSQL) or die ("Не могу выполнить запрос3");
		
	}
	$strSQL="DELETE FROM basket WHERE id_bask='".$id_bask."'";
	echo $strSQL;
	mysql_query($strSQL) or die ("Не могу выполнить запрос4");
	$uniq_ID=uniqid("ID");
	setcookie("id_bask",$uniq_ID,time()+60*60*24*14);
	$message="<tr><td bgcolor='#66cc66' align='center'>
	Ваш заказ отправлен </td></tr>";
}
}
include ("header.phtml");
echo $message;
include ("footer.phtml");
?>
	