<?header ("Content-type: text/xml");
print "<?xml version=\"1.0\" encoding =\"UTF-8\"?>";
include ("connect.phtml");
$strSQL1 = "SELECT * FROM manufacturer ORDER BY name_man";
$result1 = mysql_query($strSQL1) or die ("Не могу выполнить запрос1");
print "<прайс-лист>";
while($row = mysql_fetch_array($result1))
{
	print "<Производитель код ='".$row["id_man"]."'>".$row["name_man"];
	$strSQL2 = "SELECT id_product, name_man, name_product,price,name_cat FROM product,manufacturer,categories WHERE product.id_cat=categories.id_cat AND product.id_man=".$row["id_man"];
	$result2=mysql_query($strSQL2) or die("Не могу выполнить запрос2");
	while($row2=mysql_fetch_array($result2))
	{
		print "<товар Производитель='".$row2["name_man"]."' Название ='".$row2["name_product"]."'>";
		print "<цена>".$row2["price"]."</цена>";
		print "<категория>".$row2["name_cat"]."</категория>";
		print "</товар>";
	}
	print "</Производитель>";
}
print "</прайс-лист>";
mysql_close();
?>